### ISSUE TITLE
get_activation_link: error status 406, invalid 'Accept' header

### ISSUE THREAD

**Issue by tacensTECSOL** [thingsboard/thingsboard-python-rest-client#128]
The 'Accept' header of "get_activation_link_using_get_with_http_info" in [34372d2](https://github.com/thingsboard/thingsboard-python-rest-client/commit/34372d26354cdd2f2408a553765f5123dc19308e) is incorrect.

Calling that method now result in the following exception: 
![image](https://github.com/thingsboard/thingsboard-python-rest-client/assets/109336634/98c63f82-3777-4bb3-ada2-7ff01d99ee1b)

Reverting that specific change by accepting only 'text/plain' fixed the issue on my end.
```python
header_params['Accept'] = self.api_client.select_header_accept(['text/plain'])  # noqa: E501
```

**Comment by samson0v** [comment]
Hi @devaskim, this bug was fixed, please, use the version from the master branch.

**Comment by devaskim** [comment]
@samson0v  it isn't a bug of my interest) but thanks

**Comment by tacensTECSOL** [comment]
> Hi @tacensTECSOL, this bug was fixed, please, use the version from the master branch.

The issue is still here @samson0v, even when cloning from the master branch [c1b5572](https://github.com/thingsboard/thingsboard-python-rest-client/commit/c1b55723635c09b3125ea54abb61f277bc164904) 

Please change that part:
```python
# HTTP header `Accept`
header_params['Accept'] = self.api_client.select_header_accept(
    ['text/plain', 'application/json'])  # noqa: E501
```
https://github.com/thingsboard/thingsboard-python-rest-client/blob/master/tb_rest_client/api/api_pe/user_controller_api.py#L516

to :
```python
# HTTP header `Accept`
header_params['Accept'] = self.api_client.select_header_accept(
    ['text/plain'])  # noqa: E501
```
That single line change completely fixed the issue for me.

Regards,
Tristan
